# Generated by Django 6.0.2 on 2026-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
